engines/internal/config/routes.rb
Internal::Engine.routes.draw do

  root 'dashboard#index'

  resources :sessions, path: 'acesso'

  resources :users
  resources :administrators
  
  resources :articles
  resources :article_categories

  resources :bulletins

  resources :questions do 
    resources :anwsers
  end

  resources :simulations
  # routes for users

  resources :users do 
    resources :bookmarks
  end

  resources :user_simulations

end

engines/internal/app/models/internal/application_record.rb
module Internal
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/internal/app/models/internal/article.rb
module Internal
  class Article < ::Article

    attr_accessor :author_ids, :coauthor_ids, :collaborator_ids

    validates :title, :content, :author_ids, :category_ids, presence: true
    
    after_commit :set_authors

    private

    def set_authors
      self.article_authors.destroy_all

      update_collection!('autor', self.author_ids)  if self.author_ids.present?
      update_collection!('co_autor', self.coauthor_ids) if self.coauthor_ids.present?
      update_collection!('colaborador', self.collaborator_ids) if self.collaborator_ids.present?
    end

    def update_collection! type, collection
      collection.each do |author_id|
        self.article_authors.new({
          user_id: author_id,
          author_type: type
        }).save
      end
    end


  end
end

engines/internal/app/models/internal/article_category.rb
module Internal
  class ArticleCategory < ::ArticleCategory
    validates :name, presence: true
  end
end

engines/internal/app/models/internal/session.rb
module Internal
  class Session
    include ActiveModel::Model 

    attr_accessor :email, :password,:user_id

    validates :email, email: true, presence: true
    validates :password, presence: true
    validate  :valid_user?

    private

    def valid_user?
      user = Internal::User.where(email: self.email, password: self.password).first

      if user.present?
        self.user_id = user.id
      else 
        errors.add(:email, "E-mail ou Senha não conferem.")
      end
    end
  end
end

engines/internal/app/models/internal/user.rb
module Internal
  class User < ::User
  end
end

engines/internal/app/controllers/internal/application_controller.rb
module Internal
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    layout 'internal/application'
    
    include Pundit

    before_action :authenticate_user!

    helper_method :current_user
    
    private

    def current_user
      Internal::User.find(session[:user_id]) rescue nil
    end

    def authenticate_user!
      if !current_user.present?
        redirect_to new_session_path if controller_name != "sessions"
      end
    end
  end
end

engines/internal/app/controllers/internal/article_categories_controller.rb
require_dependency 'internal/application_controller'

module Internal
  class ArticleCategoriesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def index
      @article_categories = Internal::ArticleCategory.all
    end

    def show
    end

    def new
      @article_category = Internal::ArticleCategory.new
    end

    def create
      @article_category = Internal::ArticleCategory.new(set_params)

      if @article_category.save
        flash[:green] = t(:success)
        redirect_to action: :index
      else
        render action: :new
      end
    end

    def edit
    end

    def update

      if @article_category.update(set_params)
        flash[:green] = t(:success)
        redirect_to action: :index
      else
        render action: :edit
      end
      
    end

    def destroy
      if @article_category.destroy
        flash[:green] = t(:success)
      else 
        flash[:red] = t(:error)
      end

      redirect_to action: :index
    end

    private

    def set_params
      params.require(:article_category).permit(:name, :father_id, :enable, :portal_view, :only_user)
    end

    def set_article
      @article_category = Internal::ArticleCategory.find(params[:id])
    end

  end
end

engines/internal/app/controllers/internal/articles_controller.rb
require_dependency 'internal/application_controller'

module Internal
  class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def index
      @articles = Internal::Article.all
    end

    def show
    end

    def new
      @article = Internal::Article.new
    end

    def create
      @article = Internal::Article.new(set_params)

      if @article.save
        flash[:green] = t(:success)
        redirect_to action: :index
      else
        render action: :new
      end
    end

    def edit
    end

    def update
      if @article.update(set_params)
        flash[:green] = t(:success)
        redirect_to action: :index
      else
        render action: :edit
      end
    end

    def destroy
      if @article.destroy
        flash[:green] = t(:success)
      else 
        flash[:red] = t(:error)
      end

      redirect_to action: :index
    end

    private

    def set_params
      params.require(:article).permit(:title, :article_category_id, :content, category_ids: [], author_ids: [], coauthor_ids: [],collaborator_ids: [] )
    end

    def set_article
      @article = Internal::Article.find(params[:id])
    end

  end
end

engines/internal/app/controllers/internal/dashboard_controller.rb
require_dependency 'internal/application_controller'

module Internal
  class DashboardController < ApplicationController
    
    def index
    end

  end
end

engines/internal/app/controllers/internal/sessions_controller.rb
module Internal
  class SessionsController < ApplicationController
    
    layout 'internal/session'

    def new
      @session = Internal::Session.new
    end

    def create
      @session = Internal::Session.new(set_params)

      if @session.valid? 
        session[:user_id] = @session.user_id
        redirect_to internal.root_path
      else
        render action: :new
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to internal.root_path
    end

    private

    def set_params
      params.require(:session).permit(:email, :password)
    end
    
  end
end

engines/internal/app/controllers/internal/users_controller.rb
require_dependency 'internal/application_controller'

module Internal
  class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :destroy, :show]

    def index
      @users = Internal::User.all
    end

    def show
    end

    def new
      @user = Internal::User.new
    end

    def create
      @user = Internal::User.new(set_params)

      if @user.save
        flash[:green] = t(:success) 
        redirect_to action: :index
      else
        render action: :new
      end
    end

    def edit
    end

    def update

      if params[:user][:password].blank?
        params[:user].delete :password
        params[:user].delete :password_confirmation
      end

      if @user.update(set_params)
        flash[:green] = t(:success) 
        redirect_to action: :index
      else
        render action: :new
      end
    end

    def destroy
      if @user.destroy
        flash[:green] = t(:success) 
      else 
        flash[:red] = t(:error)
      end

      redirect_to action: :index 
    end

    private

    def set_params
      params.fetch(:user, {}).permit(:name, :username, :password, :password_confirmation, 
                                     :bio, :email, :status, :administrator, :reviewer, :student,
                                     :viewer, :author, :columnist)
    end

    def set_user
      @user = Internal::User.find(params[:id])
    end
    
  end
end

engines/internal/app/helpers/internal/application_helper.rb
module Internal
  module ApplicationHelper
  end
end

engines/internal/app/views/internal/article_categories/_form.html.haml
= simple_form_for @article_category do |f|
  .field
    = f.input :name, input_html: { placeholder: "Digite o título do artigo"}
  .fields
    .field.wide.five
      = f.input :father_id, as: :select, collection: Internal::ArticleCategory.all.order(:name), include_blank: false, include_blank: "Nenhuma"
    .field.wide.two
      = f.input :enable, as: :select, include_blank: false
    .field.wide.two
      = f.input :portal_view, as: :select, include_blank: false
    .field.wide.two
      = f.input :only_user, as: :select, include_blank: false
  .field
    = f.button :submit, data: { disable_with: t(:disable_with) }
    = link_to t(:back_button), article_categories_path, class: 'ui button', data: { disable_with: t(:disable_with) }

engines/internal/app/views/internal/article_categories/edit.html.haml
.row
  .column
    %p
      %h1 Categorias
      %small 
        %i Editar categoria 
.row
  .column
    = link_to 'Voltar para listagem de categorias', article_categories_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
.row
  .column
    .ui.segment
      = render 'form'

engines/internal/app/views/internal/article_categories/index.html.haml
.row
  .column
    %p
      %h1 Categorias de artigo
      %small 
        %i Listagem de categorias de artigo 
.row
  .column
    = link_to '+ Adicionar nova categoria', new_article_category_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
.row
  .column
    .ui.segment
      = simple_form_for url_for, method: :get do |f|
        .fields
          .field.wide.two
            = f.input :by_code, label: "Por código", input_html: { name: :by_code, value: params[:by_code]}
          .field.wide.five
            = f.input :by_title, label: "Por título", input_html: { name: :by_title, value: params[:by_title]}
          .field.wide.four
            = f.input :by_category, label: "Por categoria", as: :select, include_blank: "Todos", input_html: { name: :by_category}, selected: params[:by_category]
          .field.wide.four
            = f.input :by_autor, label: "Por autor", as: :select, collection: ::Internal::User.authors.order(:name), include_blank: "Todos", include_blank: "Todos", input_html: { name: :by_autor}, selected: params[:by_autor]
          .field.wide.four
            = f.submit "Filtrar", name: nil, class: 'ui button green button-filter', data: { disable_with: t(:disable_with_button).html_safe}
.row
  .column
    %table.ui.table.celled
      %thead
        %tr
          %th Nome
          %th.collapsing Habilitada?
          %th.collapsing Visível no portal?
          %th.collapsing Somente para usuários?
          %th
      %tbody
        - if @article_categories.present?
          - @article_categories.each do |category|
            %tr
              %td= category.name
              %td= I18n.t("label.#{category.enable}").html_safe
              %td= I18n.t("label.#{category.portal_view}").html_safe
              %td= I18n.t("label.#{category.only_user}").html_safe
              %td.collapsing
                = link_to "<i class='write icon'></i>".html_safe, edit_article_category_path(category), title: I18n.t(:edit_title), class: 'ui button icon blue mini'
                = link_to "<i class='trash icon'></i>".html_safe, article_category_path(category), method: :delete, title: I18n.t(:trash_title),class: 'ui button icon red mini', data: { disable_with: t(:disable_with_button), confirm: t(:confirm)}
        - else
          %tr 
            %td{colspan: 5}
              %i Nenhuma categoria cadastrada.

engines/internal/app/views/internal/article_categories/new.html.haml
.row
  .column
    %p
      %h1 Categorias
      %small 
        %i Adicionar nova categoria 
.row
  .column
    = link_to 'Voltar para listagem de categorias', article_categories_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
.row
  .column
    .ui.segment
      = render 'form'

engines/internal/app/views/internal/articles/_form.html.haml
= simple_form_for @article do |f|
  .field
    = f.input :category_ids, as: :select, collection: Internal::ArticleCategory.all, input_html: { multiple: true, class: 'ui fluid dropdown search'}, include_blank: "Selecione uma categoria..."
  .field
    = f.input :title, input_html: { placeholder: "Digite o título do artigo"}
  .field
    = f.input :content
  .field
    = f.input :meta_tags, as: :string
  .three.fields
    .field
      = f.input :author_ids, as: :select, collection: Internal::User.authors, input_html: { multiple: true, class: 'ui fluid dropdown search'}, selected: f.object.author_value_ids, include_blank: "Selecione..."
    .field
      = f.input :coauthor_ids, as: :select, collection: Internal::User.authors, input_html: { multiple: true, class: 'ui fluid dropdown search'}, selected: f.object.coauthor_value_ids,include_blank: "Selecione..."
    .field
      = f.input :collaborator_ids, as: :select, collection: Internal::User.authors, input_html: { multiple: true, class: 'ui fluid dropdown search'}, selected: f.object.collaborator_value_ids,include_blank: "Selecione..."
  .fields
    .field.wide.three
      = f.input :publish_date, as: :string, input_html: { class: 'date'   }
    .field.wide.three
      = f.input :revised, as: :select, include_blank: false
    .field.wide.three
      = f.input :publish, as: :select, include_blank: false
  .ui.divider.hidden
  .field
    = f.button :submit, data: { disable_with: t(:disable_with) }
    = link_to t(:back_button), articles_path, class: 'ui button', data: { disable_with: t(:disable_with) }

engines/internal/app/views/internal/articles/edit.html.haml
.row
  .column
    %p
      %h1 Artigos
      %small 
        %i Editar artigo 
.row
  .column
    = link_to 'Voltar para listagem de artigos', articles_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
.row
  .column
    .ui.segment
      = render 'form'

engines/internal/app/views/internal/articles/index.html.haml
.row
  .column
    %p
      %h1 Artigos
      %small 
        %i Listagem de usuários cadastrados 
.row
  .column
    = link_to '+ Adicionar novo artigo', new_article_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
.row
  .column
    .ui.segment
      = simple_form_for url_for, method: :get do |f|
        .fields
          .field.wide.two
            = f.input :by_code, label: "Por código", input_html: { name: :by_code, value: params[:by_code]}
          .field.wide.five
            = f.input :by_title, label: "Por título", input_html: { name: :by_title, value: params[:by_title]}
          .field.wide.four
            = f.input :by_category, label: "Por categoria", as: :select, include_blank: "Todos", input_html: { name: :by_category}, selected: params[:by_category]
          .field.wide.four
            = f.input :by_autor, label: "Por autor", as: :select, collection: ::Internal::User.authors.order(:name), include_blank: "Todos", include_blank: "Todos", input_html: { name: :by_autor}, selected: params[:by_autor]
          .field.wide.four
            = f.submit "Filtrar", name: nil, class: 'ui button green button-filter', data: { disable_with: t(:disable_with_button).html_safe}
.row
  .column
    %table.ui.table.celled
      %thead
        %tr
          %th.collapsing Cod.
          %th Título
          %th Categoria
          %th.collapsing Publicado?
          %th.collapsing Revisado?
          %th
      %tbody
        - if @articles.present?
          - @articles.each do |article|
            %tr 
              %td= article.id
              %td= article.title
              %td.collapsing
                - article.categories.each do |category|
                  .ui.label= category.name
              %td= I18n.t("label.#{article.publish}").html_safe
              %td= I18n.t("label.#{article.revised}").html_safe
              %td.collapsing
                = link_to "<i class='expand icon'></i>".html_safe, article_path(article), title: I18n.t(:view_title), class: 'ui button icon mini'
                = link_to "<i class='write icon'></i>".html_safe, edit_article_path(article), title: I18n.t(:edit_title), class: 'ui button icon blue mini'
                = link_to "<i class='trash icon'></i>".html_safe, article_path(article), method: :delete, title: I18n.t(:trash_title),class: 'ui button icon red mini', data: { disable_with: t(:disable_with_button), confirm: t(:confirm)} 
        - else
          %tr
            %td{colspan: 6}
              %i Nenhum artigo encontrado.
          

engines/internal/app/views/internal/articles/new.html.haml
.row
  .column
    %p
      %h1 Artigos
      %small 
        %i Adicionar novo artigo 
.row
  .column
    = link_to 'Voltar para listagem de artigos', articles_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
.row
  .column
    .ui.segment
      = render 'form'

engines/internal/app/views/internal/users/_form.html.haml
= simple_form_for @user do |f|
  .fields
    .field.wide.twelve
      = f.input :name, input_html: { placeholder: "Digite o nome do autor"}
    .field.wide.four
      = f.input :avatar, as: :file
  .fields
    .field.wide.four
      = f.input :email, input_html: { placeholder: "Digite o e-mail do autor"}
    .field.wide.four
      = f.input :password, input_html: { placeholder: "Digite uma senha"}
      = f.hint "Deixe em branco se não deseja alterar" if !f.object.new_record?
    .field.wide.four
      = f.input :password_confirmation, input_html: { placeholder: "Repita a senha"}
      = f.hint "Deixe em branco se não deseja alterar" if !f.object.new_record?
    .field.wide.four
      = f.input :status, as: :select, include_blank: false
  .fields
    .field.wide.four
      = f.input :administrator, as: :select, include_blank: false
    .field.wide.four
      = f.input :author, as: :select, include_blank: false
    .field.wide.four
      = f.input :student, as: :select, include_blank: false
    .field.wide.four
      = f.input :reviewer, as: :select, include_blank: false
    .field.wide.four
      = f.input :viewer, as: :select, include_blank: false
    .field.wide.four
      = f.input :columnist, as: :select, include_blank: false
  .field
    = f.input :bio
  .field
    = f.button :submit, data: { disable_with: t(:disable_with) }
    = link_to t(:back_button), users_path, class: 'ui button', data: { disable_with: t(:disable_with) }

engines/internal/app/views/internal/users/edit.html.haml
.row
  .column
    %p
      %h1 Usuários
      %small 
        %i Editar usuário 
.row
  .column
    = link_to 'Voltar para listagem de usuários', users_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
.row
  .column
    .ui.segment
      = render 'form'

engines/internal/app/views/internal/users/index.html.haml
.row
  .column
    %p
      %h1 Usuários
      %small 
        %i Listagem de usuários cadastrados 
.row
  .column
    = link_to '+ Adicionar novo usuário', new_user_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
.row
  .column
    %table.ui.table.celled
      %thead
        %tr
          %th Nome
          %th E-mail
          %th.collapsing Criado em
          %th.collapsing Administrador?
          %th.collapsing Autor?
          %th.collapsing Colunista?
          %th.collapsing Estudante?
          %th.collapsing Revisor?
          %th.collapsing Ativo?
          %th
      %tbody
        - if @users.present?
          - @users.each do |user|
            %tr
              %td.collapsing= user.name.downcase
              %td.collapsing= user.email
              %td= user.created_at.strftime("%d/%m/%Y")
              %td= I18n.t("label.#{user.administrator.to_s}").html_safe
              %td= I18n.t("label.#{user.author.to_s}").html_safe
              %td= I18n.t("label.#{user.columnist.to_s}").html_safe
              %td= I18n.t("label.#{user.student.to_s}").html_safe
              %td= I18n.t("label.#{user.reviewer.to_s}").html_safe
              %td= I18n.t("label.#{user.status.to_s}").html_safe
              %td.collapsing
                = link_to "<i class='expand icon'></i>".html_safe, user_path(user), title: I18n.t(:view_title), class: 'ui button icon mini'
                = link_to "<i class='write icon'></i>".html_safe, edit_user_path(user), title: I18n.t(:edit_title), class: 'ui button icon blue mini'
                = link_to "<i class='trash icon'></i>".html_safe, user_path(user), method: :delete, title: I18n.t(:trash_title),class: 'ui button icon red mini', data: { disable_with: t(:disable_with_button), confirm: t(:confirm)} if current_user.id != user.id
        - else
          %tr
            %td{colspan: 6}
              %i Nenhum autor cadastrado.
            
  

engines/internal/app/views/internal/users/new.html.haml
.row
  .column
    %p
      %h1 Usuários
      %small 
        %i Adicionar novo usuário 
.row
  .column
    = link_to 'Voltar para listagem de usuários', users_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
.ui.divider
.row
  .column
    .ui.segment
      = render 'form'

engines/internal/app/views/internal/users/show.html.haml
.row
  .column
    %p
      %h1 Usuários
      %small 
        %i Detalhamento de usuário 
.row
  .column
    = link_to 'Voltar para listagem de usuários', users_path, class: 'ui button blue', data: { disable_with: t(:disable_with)}
    = link_to 'Editar este usuário', edit_user_path(@user), class: 'ui button green', data: { disable_with: t(:disable_with)}
.row
  .column
    .ui.segment
      %table.ui.table
        %thead 
          %tr 
            %th Nome
            %th E-mail
        %tbody 
          %tr 
            %td #{@user.name}
            %td #{@user.email}
           
      %table.ui.table
        %thead 
          %tr 
            %th Bio
        %tbody
          %tr
            %td #{@user.bio}

      %table.ui.table
        %thead 
          %tr 
            %th.collapsing Ativo?
            %th.collapsing Administrador?
            %th.collapsing Autor?
            %th.collapsing Colunista?
            %th.collapsing Estudante?
            %th.collapsing Revisor?
        %tbody 
          %tr 
            %td= I18n.t("label.#{@user.status.to_s}").html_safe
            %td= I18n.t("label.#{@user.administrator.to_s}").html_safe
            %td= I18n.t("label.#{@user.author.to_s}").html_safe
            %td= I18n.t("label.#{@user.columnist.to_s}").html_safe
            %td= I18n.t("label.#{@user.student.to_s}").html_safe
            %td= I18n.t("label.#{@user.reviewer.to_s}").html_safe

      %table.ui.table
        %thead 
          %tr 
            %th.collapsing Artigos
        %tbody
          %tr 
            %td
              %i Nenhum artigo encontrado.

engines/internal/app/views/layouts/internal/_header.html.haml
.ui.attached.stackable.menu
  .ui.container
    = link_to image_tag('/images/cj_logo_pb.png', size: '250x100'), main_app.root_path
.ui.custom-menu.attached.stackable.menu
  .ui.container
    %a.item{href: "#{internal.root_path}"}
      Dashboard
    .ui.simple.dropdown.item
      Artigos
      %i.dropdown.icon
      .menu
        - if policy(:navigation, namespace: Internal).administrator?
          .header
            Administrativo
          %a.item{href: "#{internal.new_article_path}"}
            Novo artigo
          %a.item{href: "#{internal.articles_path}"}
            Ver todos
          %a.item{href: "#{internal.article_categories_path}"}
            Categorias
        - if policy(:navigation, namespace: Internal).author?
          .header
            Autor/Colunista
          %a.item
            Novo artigo
          %a.item
            Meus artigos
          %a.item
            Em revisão
          %a.item
            Publicados
        - if policy(:navigation, namespace: Internal).student?
          .header
            Estudo
          %a.item
            Meus favoritos
          %a.item
            Ler depois
          %a.item
            Artigos que gostei
    - if policy(:navigation, namespace: Internal).administrator?            
      .ui.simple.dropdown.item
        Boletim Jurídico
        %i.dropdown.icon
        .menu
          .header
            Administrativo 
          %a.item
            Novo boletim
          %a.item
            Ver todos
          %a.item
            Categorias  

    .ui.simple.dropdown.item
      Questões
      %i.dropdown.icon
      .menu
        - if policy(:navigation, namespace: Internal).administrator?    
          .header
            Administração
          %a.item
            Novo simulado
          %a.item
            Questões
        - if policy(:navigation, namespace: Internal).student?    
          .header
            Estudo
          %a.item
            Novo simulado
          %a.item
            Meus simulados
          %a.item
            Meu desempenho
    - if policy(:navigation, namespace: Internal).administrator? 
      .ui.simple.dropdown.item
        Usuários
        %i.dropdown.icon
        .menu
          %a.item{href: "#{internal.users_path}"}
            Gestão
    .ui.simple.dropdown.item.right
      Usuários
      %i.dropdown.icon
      .menu
        %a.item{href: "#{internal.edit_user_path(current_user)}"}
          Editar meu perfil
        %a.item{href: "#{internal.session_path(current_user)}", data: { method: :delete }}
          Sair

engines/internal/app/views/layouts/internal/application.html.haml
!!!
%html
  %head
    %title Conteúdo Jurídico
    = csrf_meta_tags
    = stylesheet_link_tag    'internal/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'internal/application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/internal/header'
    = yield

engines/internal/app/views/layouts/internal/session.html.haml
!!!
%html
  %head
    %title Conteúdo Jurídico
    = csrf_meta_tags
    = stylesheet_link_tag    'internal/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'internal/application', 'data-turbolinks-track': 'reload'
  :css
    body {
      background-color: #fff !important;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {
      max-width: 600px;
    }
  %body
    = yield